version: "3.8"

services:
  sac:
    image: sac:latest
    networks:
      - netrenassol
    environment:
      NODE_ENV: production
      PORT: "3000"
      HOST: "0.0.0.0"
      SUPABASE_URL: "https://supabase-sac.renassolnuvem.tech"
      SUPABASE_PUBLISHABLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlIiwiaWF0IjoxNzg2NzM5NjI4LCJleHAiOjE5NDQ0MTk2Mjh9.RMjt4W7N4QVInvV7CaAF4VL_pXQ2Yq0TCn53tf9sXHA"
      SUPABASE_PROJECT_ID: "sac-selfhosted"
      PUBLIC_APP_URL: "https://sac.renassolnuvem.tech"
    secrets:
      - source: sac_supabase_service_role_key_v2
        target: sac_supabase_service_role_key
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      labels:
        - traefik.enable=true
        - traefik.http.routers.sac.rule=Host(`sac.renassolnuvem.tech`)
        - traefik.http.routers.sac.entrypoints=websecure
        - traefik.http.routers.sac.tls.certresolver=letsencryptresolver
        - traefik.http.routers.sac.service=sac
        - traefik.http.services.sac.loadbalancer.server.port=3000
        - traefik.http.services.sac.loadbalancer.passHostHeader=true

networks:
  netrenassol:
    external: true
    name: NetRenassol

secrets:
  sac_supabase_service_role_key_v2:
    external: true
