/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedOperadoresRouteImport } from './routes/_authenticated/operadores'
import { Route as AuthenticatedIntegracaoRouteImport } from './routes/_authenticated/integracao'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAlertasRouteImport } from './routes/_authenticated/alertas'
import { Route as AuthenticatedConversasIndexRouteImport } from './routes/_authenticated/conversas.index'
import { Route as AuthenticatedConversasIdRouteImport } from './routes/_authenticated/conversas.$id'
import { Route as ApiPublicWebhookRecvTokenRouteImport } from './routes/api/public/webhook/recv/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/_authenticated/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOperadoresRoute = AuthenticatedOperadoresRouteImport.update({
  id: '/_authenticated/operadores',
  path: '/operadores',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIntegracaoRoute = AuthenticatedIntegracaoRouteImport.update({
  id: '/_authenticated/integracao',
  path: '/integracao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/_authenticated/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAlertasRoute = AuthenticatedAlertasRouteImport.update({
  id: '/_authenticated/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConversasIndexRoute =
  AuthenticatedConversasIndexRouteImport.update({
    id: '/_authenticated/conversas/',
    path: '/conversas/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedConversasIdRoute =
  AuthenticatedConversasIdRouteImport.update({
    id: '/_authenticated/conversas/$id',
    path: '/conversas/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhookRecvTokenRoute =
  ApiPublicWebhookRecvTokenRouteImport.update({
    id: '/api/public/webhook/recv/$token',
    path: '/api/public/webhook/recv/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integracao': typeof AuthenticatedIntegracaoRoute
  '/operadores': typeof AuthenticatedOperadoresRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/conversas/$id': typeof AuthenticatedConversasIdRoute
  '/conversas/': typeof AuthenticatedConversasIndexRoute
  '/api/public/webhook/recv/$token': typeof ApiPublicWebhookRecvTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integracao': typeof AuthenticatedIntegracaoRoute
  '/operadores': typeof AuthenticatedOperadoresRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/conversas/$id': typeof AuthenticatedConversasIdRoute
  '/conversas': typeof AuthenticatedConversasIndexRoute
  '/api/public/webhook/recv/$token': typeof ApiPublicWebhookRecvTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/alertas': typeof AuthenticatedAlertasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/integracao': typeof AuthenticatedIntegracaoRoute
  '/_authenticated/operadores': typeof AuthenticatedOperadoresRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/conversas/$id': typeof AuthenticatedConversasIdRoute
  '/_authenticated/conversas/': typeof AuthenticatedConversasIndexRoute
  '/api/public/webhook/recv/$token': typeof ApiPublicWebhookRecvTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/configuracoes'
    | '/dashboard'
    | '/integracao'
    | '/operadores'
    | '/relatorios'
    | '/conversas/$id'
    | '/conversas/'
    | '/api/public/webhook/recv/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/configuracoes'
    | '/dashboard'
    | '/integracao'
    | '/operadores'
    | '/relatorios'
    | '/conversas/$id'
    | '/conversas'
    | '/api/public/webhook/recv/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/alertas'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/integracao'
    | '/_authenticated/operadores'
    | '/_authenticated/relatorios'
    | '/_authenticated/conversas/$id'
    | '/_authenticated/conversas/'
    | '/api/public/webhook/recv/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedAlertasRoute: typeof AuthenticatedAlertasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIntegracaoRoute: typeof AuthenticatedIntegracaoRoute
  AuthenticatedOperadoresRoute: typeof AuthenticatedOperadoresRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedConversasIdRoute: typeof AuthenticatedConversasIdRoute
  AuthenticatedConversasIndexRoute: typeof AuthenticatedConversasIndexRoute
  ApiPublicWebhookRecvTokenRoute: typeof ApiPublicWebhookRecvTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/operadores': {
      id: '/_authenticated/operadores'
      path: '/operadores'
      fullPath: '/operadores'
      preLoaderRoute: typeof AuthenticatedOperadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/integracao': {
      id: '/_authenticated/integracao'
      path: '/integracao'
      fullPath: '/integracao'
      preLoaderRoute: typeof AuthenticatedIntegracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/alertas': {
      id: '/_authenticated/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AuthenticatedAlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/conversas/': {
      id: '/_authenticated/conversas/'
      path: '/conversas'
      fullPath: '/conversas/'
      preLoaderRoute: typeof AuthenticatedConversasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/conversas/$id': {
      id: '/_authenticated/conversas/$id'
      path: '/conversas/$id'
      fullPath: '/conversas/$id'
      preLoaderRoute: typeof AuthenticatedConversasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/recv/$token': {
      id: '/api/public/webhook/recv/$token'
      path: '/api/public/webhook/recv/$token'
      fullPath: '/api/public/webhook/recv/$token'
      preLoaderRoute: typeof ApiPublicWebhookRecvTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedAlertasRoute: AuthenticatedAlertasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIntegracaoRoute: AuthenticatedIntegracaoRoute,
  AuthenticatedOperadoresRoute: AuthenticatedOperadoresRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedConversasIdRoute: AuthenticatedConversasIdRoute,
  AuthenticatedConversasIndexRoute: AuthenticatedConversasIndexRoute,
  ApiPublicWebhookRecvTokenRoute: ApiPublicWebhookRecvTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
