/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as IntegracaoRouteImport } from './routes/integracao'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConversasRouteImport } from './routes/conversas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConversasIdRouteImport } from './routes/conversas.$id'
import { Route as ApiPublicWebhookRecvTokenRouteImport } from './routes/api/public/webhook/recv/$token'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracaoRoute = IntegracaoRouteImport.update({
  id: '/integracao',
  path: '/integracao',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversasRoute = ConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversasIdRoute = ConversasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ConversasRoute,
} as any)
const ApiPublicWebhookRecvTokenRoute =
  ApiPublicWebhookRecvTokenRouteImport.update({
    id: '/api/public/webhook/recv/$token',
    path: '/api/public/webhook/recv/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conversas': typeof ConversasRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/integracao': typeof IntegracaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/conversas/$id': typeof ConversasIdRoute
  '/api/public/webhook/recv/$token': typeof ApiPublicWebhookRecvTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conversas': typeof ConversasRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/integracao': typeof IntegracaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/conversas/$id': typeof ConversasIdRoute
  '/api/public/webhook/recv/$token': typeof ApiPublicWebhookRecvTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conversas': typeof ConversasRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/integracao': typeof IntegracaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/conversas/$id': typeof ConversasIdRoute
  '/api/public/webhook/recv/$token': typeof ApiPublicWebhookRecvTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/configuracoes'
    | '/conversas'
    | '/dashboard'
    | '/integracao'
    | '/relatorios'
    | '/conversas/$id'
    | '/api/public/webhook/recv/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/configuracoes'
    | '/conversas'
    | '/dashboard'
    | '/integracao'
    | '/relatorios'
    | '/conversas/$id'
    | '/api/public/webhook/recv/$token'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/configuracoes'
    | '/conversas'
    | '/dashboard'
    | '/integracao'
    | '/relatorios'
    | '/conversas/$id'
    | '/api/public/webhook/recv/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConversasRoute: typeof ConversasRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  IntegracaoRoute: typeof IntegracaoRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ApiPublicWebhookRecvTokenRoute: typeof ApiPublicWebhookRecvTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracao': {
      id: '/integracao'
      path: '/integracao'
      fullPath: '/integracao'
      preLoaderRoute: typeof IntegracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversas': {
      id: '/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof ConversasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversas/$id': {
      id: '/conversas/$id'
      path: '/$id'
      fullPath: '/conversas/$id'
      preLoaderRoute: typeof ConversasIdRouteImport
      parentRoute: typeof ConversasRoute
    }
    '/api/public/webhook/recv/$token': {
      id: '/api/public/webhook/recv/$token'
      path: '/api/public/webhook/recv/$token'
      fullPath: '/api/public/webhook/recv/$token'
      preLoaderRoute: typeof ApiPublicWebhookRecvTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ConversasRouteChildren {
  ConversasIdRoute: typeof ConversasIdRoute
}

const ConversasRouteChildren: ConversasRouteChildren = {
  ConversasIdRoute: ConversasIdRoute,
}

const ConversasRouteWithChildren = ConversasRoute._addFileChildren(
  ConversasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConversasRoute: ConversasRouteWithChildren,
  DashboardRoute: DashboardRoute,
  IntegracaoRoute: IntegracaoRoute,
  RelatoriosRoute: RelatoriosRoute,
  ApiPublicWebhookRecvTokenRoute: ApiPublicWebhookRecvTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
