// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkabtowunbwstgouytcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrYWJ0b3d1bmJ3c3Rnb3V5dGNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQwMTM1NDYsImV4cCI6MjA4OTU4OTU0Nn0.bdcEzt8J4S4vTEWehFVd7F3hwMVQwA5MjnroUUY9cGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});