// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client. Requires the service role key so privileged
// server functions never silently fall back to anon/public permissions.
// Use this for server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
  const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

  const key = SUPABASE_SERVICE_ROLE_KEY ?? SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !key) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!key ? ['SUPABASE_SERVICE_ROLE_KEY or SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Check the Supabase project connection.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  if (!SUPABASE_SERVICE_ROLE_KEY) {
    console.warn('[Supabase] SUPABASE_SERVICE_ROLE_KEY missing; falling back to publishable key (RLS enforced).');
  }

  return createClient<Database>(SUPABASE_URL, key, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;
let _supabaseAdminCacheKey: string | undefined;

// Server-side Supabase client. Requires SUPABASE_SERVICE_ROLE_KEY and bypasses RLS.
// SECURITY: Only use this from server-side operations, never expose to client code.
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    const cacheKey = `${process.env.SUPABASE_URL ?? ''}:${process.env.SUPABASE_SERVICE_ROLE_KEY ?? ''}`;
    if (!_supabaseAdmin || _supabaseAdminCacheKey !== cacheKey) {
      _supabaseAdmin = createSupabaseAdminClient();
      _supabaseAdminCacheKey = cacheKey;
    }
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
